// Generated by LiveScript 1.2.0
var update;
update = null;
$(document).ready(function(){
  var color;
  color = d3.scale.category20();
  return d3.json('http://kcwu.csie.org/~kcwu/ircstat/g0v-count.json', function(data){
    var ref$, w, h, max, it, nick, svg, root, draw;
    ref$ = [$('#content').width(), $('#content').height()], w = ref$[0], h = ref$[1];
    data = data.by_nick;
    max = d3.max((function(){
      var i$, ref$, len$, results$ = [];
      for (i$ = 0, len$ = (ref$ = data).length; i$ < len$; ++i$) {
        it = ref$[i$];
        results$.push(it[1]);
      }
      return results$;
    }()));
    data = data.map(function(it){
      var ref$, ref1$;
      return {
        text: it[0],
        size: 10 + ((ref$ = w / 2) < (ref1$ = h / 2) ? ref$ : ref1$) * it[1] / max
      };
    });
    nick = data.map(function(it){
      return it.text.toLowerCase();
    }).sort(function(a, b){
      if (a > b) {
        return 1;
      } else if (a === b) {
        return 0;
      } else {
        return -1;
      }
    });
    d3.select('#name').selectAll('option').data(nick).enter().append('option').attr('value', function(it){
      return it;
    }).text(function(it){
      return it;
    });
    svg = d3.select('#content').append('svg').attr('width', '100%').attr('height', '100%');
    root = svg.append('g').attr('transform', "translate(" + w / 2 + "," + h / 2 + ")");
    update = function(){
      var name;
      name = $('#name').val();
      return root.selectAll('text.cloud').style('stroke-width', function(it){
        if (it.text === name) {
          return '3px';
        } else {
          return '0';
        }
      }).style('stroke', '#f00');
    };
    draw = function(){
      var x$;
      x$ = root.selectAll('text.cloud').data(data);
      x$.exit().remove();
      x$.enter().append('text').attr('class', 'cloud').style('font-size', function(it){
        return it.size + "px";
      }).style('font-family', "century gothic").style('fill', function(d, i){
        return color(i);
      }).attr('text-anchor', "middle").attr('transform', function(it){
        return "translate(" + it.x + "," + it.y + ") rotate(" + it.rotate + ")";
      }).text(function(it){
        return it.text;
      });
      return x$;
    };
    return d3.layout.cloud().size([w, h]).words(data).padding(0).rotate(0).font("century gothic").fontSize(function(it){
      return it.size;
    }).on('end', draw).start();
  });
});