// Generated by LiveScript 1.2.0
var main;
main = function($scope, $sce){
  $scope.open = function(href){
    $scope.iframehref = $sce.trustAsResourceUrl("http://ptt.cc/bbs/Gossiping/" + href + ".html");
    console.log($scope.iframehref);
    return setTimeout(function(){
      return $('#postcontent').modal('show');
    }, 0);
  };
  $scope.click = function(id){
    $scope.target = id;
    return $scope.post = $scope.data.relate[id];
  };
  return d3.json('suspect.json', function(d){
    return $scope.$apply(function(){
      $scope.data = d;
      return $scope.suspect = d.suspect.filter(function(it){
        return it[1] > 100;
      }).sort(function(a, b){
        return b[1] - a[1];
      });
    });
  });
};