// Generated by LiveScript 1.2.0
var main;
main = function($scope, $interval, $http){
  var mapOption, simdate, mapStyle, map, overlay;
  mapOption = {
    center: new google.maps.LatLng(23.624146, 120.320623),
    zoom: 7,
    minZoom: 7,
    maxZoom: 18,
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    panControlOptions: {
      position: google.maps.ControlPosition.LEFT_CENTER
    },
    zoomControlOptions: {
      position: google.maps.ControlPosition.LEFT_CENTER
    },
    mapTypeControlOptions: {
      position: google.maps.ControlPosition.LEFT_CENTER
    }
  };
  simdate = function(date){
    return date.getYear() + 1900;
  };
  mapStyle = [
    {
      "featureType": "road",
      "stylers": [{
        "saturation": -100
      }]
    }, {
      "featureType": "poi",
      "stylers": [{
        "saturation": -100
      }]
    }, {
      "featureType": "transit",
      "stylers": [{
        "saturation": -100
      }]
    }
  ];
  mapStyle = [
    {
      "featureType": "water",
      "stylers": [
        {
          "hue": '#1900ff'
        }, {
          "lightness": -86
        }, {
          "saturation": -80
        }
      ]
    }, {
      "featureType": "landscape",
      "stylers": [
        {
          "lightness": -47
        }, {
          "hue": '#dd3d00'
        }, {
          "saturation": -80
        }
      ]
    }, {
      "featureType": "poi",
      "stylers": [
        {
          "saturation": -100
        }, {
          "lightness": -30
        }
      ]
    }, {
      "featureType": "road",
      "stylers": [
        {
          "weight": 0.3
        }, {
          "saturation": -48
        }, {
          "lightness": -0
        }, {
          "hue": '#dd4400'
        }
      ]
    }
  ];
  map = new google.maps.Map(document.getElementById('mainmap'), mapOption);
  map.set('styles', mapStyle);
  overlay = import$(new google.maps.OverlayView(), {
    info: {},
    onAdd: function(){
      this.root = this.getPanes().overlayLayer;
      this.svg = d3.select(this.root).append('svg').attr({
        width: "1400px",
        height: "1200px",
        "viewBox": "0 0 1400 1200"
      });
      this.svg.style({
        position: "absolute"
      });
      this.info.prj = d3.geo.mercator().center([120.3202, 22.7199]).scale(335000);
      return this.info.path = d3.geo.path().projection(this.info.prj);
    },
    initNode: function(data){
      var x$;
      this.data = data;
      x$ = this.svg.selectAll('circle').data(this.data);
      x$.enter().append('circle');
      this.svg.selectAll('text').data(this.data).enter().append('text');
      return this.svg.selectAll('circle').attr({
        cx: 1,
        cy: 1,
        r: 1,
        fill: 'rgba(255,128,64,0.3)',
        stroke: 'rgba(255,0,0,1)',
        "stroke-width": '2.5px',
        "stroke-dasharray": "100 2 2 2",
        opacity: 0.9
      });
    },
    ll2p: function(lat, lng, prj){
      var ret;
      return ret = prj.fromLatLngToDivPixel(new google.maps.LatLng(lat, lng));
    },
    bound2p: function(bound){
      var prj, ne, sw, p1, p2;
      prj = this.getProjection();
      ne = bound.getNorthEast();
      sw = bound.getSouthWest();
      p1 = this.ll2p(ne.lat(), sw.lng(), prj);
      p2 = this.ll2p(sw.lat(), ne.lng(), prj);
      return [p1, p2];
    },
    tick: 0,
    draw: function(){
      var prj, ref$, p1, p2, w, h, b1, b2, now, nowt, this$ = this;
      prj = this.getProjection();
      ref$ = this.bound2p(map.getBounds()), p1 = ref$[0], p2 = ref$[1];
      ref$ = [p2.x - p1.x, p2.y - p1.y], w = ref$[0], h = ref$[1];
      b1 = this.ll2p(22.7595, 120.23795080859372, prj);
      b2 = this.ll2p(22.5698, 120.409450, prj);
      now = this.svg.selectAll('circle').filter(function(d, i){
        return i === this$.tick;
      });
      nowt = this.svg.selectAll('text').filter(function(d, i){
        return i === this$.tick;
      });
      if (overlay.data) {
        this.tick = (this.tick + 1) % overlay.data.length;
      }
      now.attr({
        cx: function(d, i){
          var v;
          v = this$.ll2p(d.loc.lat(), d.loc.lng(), prj);
          return v.x;
        },
        cy: function(d, i){
          var v;
          v = this$.ll2p(d.loc.lat(), d.loc.lng(), prj);
          return v.y;
        },
        r: function(){
          return 10;
        },
        opacity: 1
      });
      nowt.attr({
        x: 100,
        y: 60,
        opacity: 1,
        "dominant-baseline": "central",
        "font-size": function(d, i){
          var ref$, ref1$;
          return (ref$ = (ref1$ = Math.sqrt(d.casualty.total) * 3) > 20 ? ref1$ : 20) < 60 ? ref$ : 60;
        }
      }).text(function(it){
        return simdate(it.date) + " " + it.name;
      });
      now.transition().ease('cubic-out').duration(1000).attr({
        opacity: 0.5,
        r: function(d, i){
          return 10 + 7 * (d.casualty.total - 10) / 8;
        }
      }).transition().ease('linear').duration(2000).attr({
        opacity: 0.0,
        r: function(d, i){
          return d.casualty.total;
        }
      });
      return nowt.transition().duration(2000).attr({
        y: 400,
        opacity: 0.6
      }).transition().duration(1000).attr({
        opacity: 0
      });
    }
  });
  overlay.setMap(map);
  $interval(function(){
    return overlay.draw();
  }, 500);
  return $http({
    url: 'https://spreadsheets.google.com/feeds/list/1p0DNKBt4oNfDBgHv4ZXH-vu0bJ_PtxFFXCL7o4O_Cxo/1/public/values?alt=json',
    method: 'GET'
  }).success(function(d){
    var data;
    data = d.feed.entry.map(function(it){
      var date, ret, casualty, lat, lng, name, loc;
      date = it.gsx$日期.$t.replace(/[年月]/g, '/');
      date = date.replace(/[日]/g, '');
      date = new Date(date);
      ret = /(?:(\d+)死)?(?:(\d+)傷)?(?:(\d+)生還)?/.exec(it.gsx$死傷.$t);
      casualty = {
        die: parseInt((ret && ret[1]) || 0),
        hurt: parseInt((ret && ret[2]) || 0),
        live: parseInt((ret && ret[3]) || 0)
      };
      casualty.total = casualty.die + casualty.hurt;
      lat = parseFloat(it.gsx$緯度.$t || 0);
      lng = parseFloat(it.gsx$經度.$t || 0);
      name = (it.gsx$短名.$t || it.gsx$事件.$t).trim();
      loc = new google.maps.LatLng(lat, lng);
      return {
        name: name,
        date: date,
        casualty: casualty,
        lat: lat,
        lng: lng,
        loc: loc
      };
    });
    data = data.filter(function(it){
      return it.lat && it.lng && it.casualty.total;
    });
    return overlay.initNode(data);
  });
};
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}