// Generated by LiveScript 1.2.0
var mainCtrl;
mainCtrl = function($scope){
  return $scope.brief = [
    {
      title: "CSS Flexbox Playgroud",
      desc: "Play with CSS flex layout various configuration",
      path: "flex"
    }, {
      title: "X3Dom with D3js",
      desc: "3D Banana with D3js fisheye plugin and Angularjs",
      path: "banana"
    }, {
      title: "PTT User Analysis",
      desc: "Find out users that always stand against other people",
      path: "ptt-user"
    }, {
      title: "NSC Project Allowance 2",
      desc: "Visualization of NSC Allowance that showing their change over time",
      path: "nsc-2"
    }, {
      title: "D3js with Maps",
      desc: "Dorling cartogram and Google maps demonstration",
      path: "dorling"
    }, {
      title: "Highway ETC Fee",
      desc: "Calculate highway ETC fee",
      path: "highway"
    }, {
      title: "Connected Scatter Plot",
      desc: "Use connected scatter plot to show time series of corelated variables.",
      path: "scatter"
    }, {
      title: "Angular + D3js",
      desc: "Render taiwan counties boundary using topojson + d3 and angularjs. Also use d3.layout.fisheye.",
      path: "ajd3"
    }, {
      title: "CSS3 Animation",
      desc: "Implement several types of animation by CSS3, such as bouncing, flipping, swifting, etc.",
      path: "animation"
    }, {
      title: "IRC Nick Cloud",
      desc: "Render IRC nicknames in word cloud, sizing them according to their active status in the channel.",
      path: "cloud"
    }, {
      title: "Interpellation Statistics",
      desc: "Topics of interpellation from specific group of legislators. Use crossfilter.js, and twgeojson.",
      path: "crossfilter"
    }, {
      title: "Type of Families over Time",
      desc: "Visualization of family types changes between 2001 to 2012",
      path: "family"
    }, {
      title: "List of Hiking Trail in Taipei",
      desc: "Compare length and check POI of each hiking trail at the same time. Use d3.layout.fisheye.",
      path: "hiking"
    }, {
      title: "Public Nuisance Query",
      desc: "Nearby public nuisance status. Use Google map API v3. Only available on local server.",
      path: "home-env"
    }, {
      title: "IRC Nicks Connections",
      desc: "Visualize connections between different IRC nicknames. Use d3.layout.force.",
      path: "ircstat"
    }, {
      title: "CSS3 Drawn Kirby",
      desc: "A Kirby portrait with Pure CSS3.",
      path: "kirby"
    }, {
      title: "Geographic Blocks",
      desc: "A simple example of rendering Taiwan geographic blocks. Use topojson.js with D3js 3.0.8",
      path: "map"
    }, {
      title: "Amount of MRT Passengers",
      desc: "Visualization of passengers statistics in each MRT station, since 2000. Use d3.layout.force.",
      path: "mrt"
    }, {
      title: "NSC Project Allowance",
      desc: "Visualization of National Science Council Allowance for each institute since 1990. Use d3.layout.bubble",
      path: "nsc"
    }, {
      title: "Nearby POI",
      desc: "Visualization of nearby point of interests, by their distance.",
      path: "roadmap"
    }, {
      title: "Word Cloud Transition",
      desc: "Demo of word cloud transition using topic that legislators are interested in. Use d3.layout.cloud.",
      path: "tts"
    }, {
      title: "Reason of Unemployment",
      desc: "Compare between methods for data comparison, using reason of unemployment as an example.",
      path: "jobless"
    }, {
      title: "IRC Activity by Weekday",
      desc: "Visualize IRC Activity with heatmap, categorized by weekday. Used in G0VIS.",
      path: "calendar"
    }, {
      title: "SVG Animation",
      desc: "Animate SVG with 4 approaches: JS+SMIL, AngujarJS+SMIL, D3js, Pure AngularJS.",
      path: "svg-animate"
    }, {
      title: "Put MRT Flow in 3D",
      desc: "Render MRT Flow in 3D heatmap. Use javascript-surface-plot lib.",
      path: "3dplot"
    }, {
      title: "Surveillance Camera",
      desc: "List locations of all surveillance Cameras. Data Credit: Mimi",
      path: "monitor"
    }
  ];
};