// Generated by LiveScript 1.2.0
var mapCtrl;
mapCtrl = function($scope){
  import$($scope, {
    geoblock: [],
    fish: d3.fisheye.circular().radius(200).focus([450, 300]),
    prj: function(arg$){
      var x, y, ref$;
      x = arg$[0], y = arg$[1];
      ref$ = d3.geo.mercator().center([120.979531, 23.978567]).scale(50000)([x, y]), x = ref$[0], y = ref$[1];
      ref$ = $scope.fish({
        x: x,
        y: y
      }), x = ref$.x, y = ref$.y;
      return [x, y];
    },
    color: d3.scale.category20c(),
    render: function(){
      return $scope.geoblock = $scope.topo.features.map(function(it){
        return [$scope.color(it.properties.COUNTYNAME), $scope.path(it)];
      });
    },
    mousemove: function(){
      $scope.fish.focus([event.x, event.y]);
      return $scope.render();
    }
  });
  $scope.path = d3.geo.path().projection($scope.prj);
  return d3.json('twCounty2010.topo.json', function(data){
    return $scope.$apply(function(){
      $scope.topo = topojson.feature(data, data.objects["twCounty2010.geo"]);
      return $scope.render();
    });
  });
};
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}