// Generated by LiveScript 1.2.0
var mainCtrl, ircCtrl;
mainCtrl = function($scope){};
ircCtrl = function($scope, $http, $element){
  import$($scope, {
    week: {
      th: ['一', '二', '三', '四', '五', '六', '日'],
      yHash: {},
      mHash: {},
      hover: {
        map: d3.scale.linear().domain([0, 300]).range([50, 250]),
        cur: {
          v: 0,
          d: "-"
        },
        setter: null,
        set: function(it){
          var this$ = this;
          if (!it) {
            this.setter = setTimeout(function(){
              this$.setter = null;
              return $scope.$apply(function(){
                return this$.cur = {
                  v: 0,
                  d: "-"
                };
              });
            }, 1000);
          } else if (this.setter) {
            clearTimeout(this.setter);
            this.setter = null;
          }
          import$(this.cur, it);
          return this.cur.tx = this.map(this.cur.x);
        }
      }
    }
  });
  return $http.get('g0v-count.json').success(function(data){
    var len, weekday, offset, dmonth, v, ref$, min, max;
    len = data.by_date_per_day.length;
    weekday = data.by_date_per_day.slice(len - 259, len - 1);
    offset = (moment(weekday[0][0]).weekday() + 6) % 7;
    dmonth = 0;
    $scope.date = weekday.map(function(d, i){
      var m, ref$, year, month, x, y;
      i += offset;
      m = moment(d[0]);
      ref$ = [m.year(), m.month() + 1], year = ref$[0], month = ref$[1];
      if (!(month in $scope.week.mHash)) {
        dmonth += 2;
        $scope.week.mHash[month] = dmonth + parseInt((i % 280) / 7) * 7;
      }
      ref$ = [dmonth + parseInt((i % 280) / 7) * 7, (i % 7) * 7 + parseInt(i / 280) * 60], x = ref$[0], y = ref$[1];
      if (!(year in $scope.week.yHash)) {
        $scope.week.yHash[year] = x;
      }
      return {
        y: y,
        x: x,
        v: d[1],
        d: d[0]
      };
    });
    v = $scope.date.map(function(it){
      return it.v;
    });
    ref$ = [d3.min(v), d3.max(v)], min = ref$[0], max = ref$[1];
    $scope.week.dayFrom = moment($scope.date[0].d).format('L');
    $scope.week.dayTil = moment((ref$ = $scope.date)[ref$.length - 1].d).format('L');
    return $scope.heatColor = d3.scale.linear().domain([min, (2 * min + max) / 3, (min + 2 * max) / 3, max]).range(['#EEEEEE', '#D6E685', '#8CC665', '#1E6823']);
  });
};
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}