// Generated by LiveScript 1.2.0
var x, main;
x = null;
main = function($scope, $http){
  var ref$, w, h, m;
  ref$ = [$(window).width() * 0.8, $(window).height() * 0.8, 70], w = ref$[0], h = ref$[1], m = ref$[2];
  return $http.get('data.json').success(function(data){
    var sorter, sort, i$, len$, item, days, res$, it, lvs, xAxis, yAxis, color, cont, x$, y$, z$, z1$, z2$, tops, mrks, name1, name2, day, init, render;
    x = data;
    sorter = function(a, b, idx, lv){
      var v, u;
      if (idx.length === lv) {
        return 0;
      }
      v = idx[lv];
      if (isNaN(a[v])) {
        u = a[v] < b[v]
          ? 1
          : a[v] > b[v]
            ? -1
            : sorter(a, b, idx, lv + 1);
      } else {
        u = ~~b[v] - ~~a[v];
        if (u === 0) {
          u = sorter(a, b, idx, lv + 1);
        }
      }
      return u;
    };
    sort = function(idx){
      var i$, ref$, len$, i, item, results$ = [];
      data.sort(function(a, b){
        return sorter(a, b, idx, 0);
      });
      for (i$ = 0, len$ = (ref$ = data).length; i$ < len$; ++i$) {
        i = i$;
        item = ref$[i$];
        results$.push(item[9] = i);
      }
      return results$;
    };
    for (i$ = 0, len$ = data.length; i$ < len$; ++i$) {
      item = data[i$];
      item.push(0);
    }
    sort([6, 2]);
    console.log((function(){
      var i$, ref$, len$, results$ = [];
      for (i$ = 0, len$ = (ref$ = data).length; i$ < len$; ++i$) {
        item = ref$[i$];
        results$.push(item[2]);
      }
      return results$;
    }()));
    res$ = [];
    for (i$ = 0, len$ = data.length; i$ < len$; ++i$) {
      it = data[i$];
      res$.push(it[6]);
    }
    days = res$;
    res$ = [];
    for (i$ = 0, len$ = data.length; i$ < len$; ++i$) {
      it = data[i$];
      res$.push(it[0]);
    }
    lvs = res$;
    xAxis = d3.scale.linear().domain([0, data.length - 1]).range([w - m, m]);
    yAxis = d3.scale.linear().domain([d3.min(days), d3.max(days)]).range([h - m, m * 2]);
    color = d3.scale.ordinal().range(['#5b7', '#d64']);
    cont = d3.select('#container');
    x$ = cont.selectAll('div.tops').data(data);
    x$.exit().remove();
    x$.enter().append('div').attr('class', 'tops');
    y$ = cont.selectAll('div.mrks').data(data);
    y$.exit().remove();
    y$.enter().append('div').attr('class', 'mrks');
    z$ = cont.selectAll('div.name1').data(data);
    z$.exit().remove();
    z$.enter().append('div').attr('class', 'name1');
    z1$ = cont.selectAll('div.name2').data(data);
    z1$.exit().remove();
    z1$.enter().append('div').attr('class', 'name2');
    z2$ = cont.selectAll('div.day').data(data);
    z2$.exit().remove();
    z2$.enter().append('div').attr('class', 'day');
    tops = cont.selectAll('div.tops');
    mrks = cont.selectAll('div.mrks');
    name1 = cont.selectAll('div.name1');
    name2 = cont.selectAll('div.name2');
    day = cont.selectAll('div.day');
    init = function(){
      var x$, y$, z$, z1$, z2$;
      x$ = cont.selectAll('div.name1');
      x$.style('width', '60px');
      x$.style('height', function(){
        return "21px";
      });
      x$.text(function(it){
        return it[4] + "";
      });
      y$ = cont.selectAll('div.name2');
      y$.style('width', '60px');
      y$.style('height', function(){
        return "21px";
      });
      y$.text(function(it){
        return it[5] + "";
      });
      z$ = cont.selectAll('div.day');
      z$.style('width', '60px');
      z$.style('height', function(){
        return "21px";
      });
      z$.text(function(it){
        return it[6] + "天";
      });
      z1$ = cont.selectAll('div.tops');
      z1$.style('width', '40px');
      z1$.style('height', function(){
        return "21px";
      });
      z1$.style('background', function(it){
        return "url(mark-top-" + (it[2] === '542旅' ? 1 : 2) + ".png) center bottom";
      });
      z2$ = cont.selectAll('div.mrks');
      z2$.style('width', '40px');
      z2$.style('height', function(it){
        return (1 + h - m - yAxis(it[6]) + 27) + "px";
      });
      z2$.style('background', function(it){
        return "url(mark-" + (it[0] < 11 ? 'general' : 'sergeant') + "-" + (it[2] === '542旅' ? 1 : 2) + ".png) center bottom";
      });
      return z2$;
    };
    render = function(){
      cont.selectAll('div.name1').transition().duration(400).style('left', function(it){
        return (xAxis(it[9]) - 30) + "px";
      }).style('top', function(){
        return (h - m + 10 + 27) + "px";
      });
      cont.selectAll('div.name2').transition().duration(400).style('left', function(it){
        return (xAxis(it[9]) - 30) + "px";
      }).style('top', function(){
        return (h - m + 25 + 27) + "px";
      });
      cont.selectAll('div.day').transition().duration(400).style('left', function(it){
        return (xAxis(it[9]) - 30) + "px";
      }).style('top', function(it){
        return (yAxis(it[6]) - 41) + "px";
      });
      cont.selectAll('div.tops').transition().duration(400).style('left', function(it){
        return (xAxis(it[9]) - 20) + "px";
      }).style('top', function(it){
        return (yAxis(it[6]) - 21) + "px";
      });
      return cont.selectAll('div.mrks').transition().duration(400).style('left', function(it){
        return (xAxis(it[9]) - 20) + "px";
      }).style('top', function(it){
        return yAxis(it[6]) + "px";
      });
    };
    init();
    render();
    /*set-interval (->
      sort [parseInt(Math.random!*9),parseInt(Math.random!*9)]
      render!
    ), 1000*/
    return $scope.sort = function(array){
      sort(array);
      return render();
    };
  });
};