// Generated by LiveScript 1.2.0
var scope, main, movehandle;
scope = null;
main = function($scope){
  scope = $scope;
  $scope.fish = d3.fisheye.circular().radius(200).focus([-50, -50]);
  $scope.coordindex = banana.coordindex.join(" ");
  $scope.rawPoint = banana.point;
  $scope.point = new Array($scope.rawPoint.length);
  $scope.vector = banana.vector.join(" ");
  $scope.morph = function(){
    var len, i$, i, ref$, x, y, z, results$ = [];
    len = parseInt($scope.rawPoint.length / 3) + 1;
    console.log($scope.rawPoint.length);
    console.log(len);
    for (i$ = 0; i$ < len; ++i$) {
      i = i$;
      ref$ = $scope.fish({
        x: $scope.rawPoint[i * 3],
        y: $scope.rawPoint[i * 3 + 1]
      }), x = ref$.x, y = ref$.y;
      z = $scope.rawPoint[i * 3 + 2];
      $scope.point[i * 3] = x;
      $scope.point[i * 3 + 1] = y;
      results$.push($scope.point[i * 3 + 2] = z);
    }
    return results$;
  };
  $scope.morph();
  return $scope.mousemove = function(event){
    $scope.fish.focus([-event.x / 10, -event.y / 10]);
    return $scope.morph();
  };
};
movehandle = function(e){
  if (scope) {
    console.log(e);
    return scope.$apply(function(){
      return scope.mousemove(e);
    });
  }
};