// Generated by LiveScript 1.2.0
var mainCtrl;
mainCtrl = function($scope){
  var radius;
  radius = 140;
  $scope.radiusFilter = function(it){
    return it.value < 12;
  };
  $scope.sizeFilter = function(it){
    return it.dx < 33 || it.dy < 12;
  };
  $scope.randomDate = function(){
    if ($scope.serialTimer) {
      clearInterval($scope.serialTimer);
    }
    $scope.serialTimer = null;
    return $scope.current = $scope.data[parseInt(Math.random() * $scope.data.length)];
  };
  $scope.serial = -1;
  $scope.serialTimer = null;
  $scope.serialDate = function(){
    if ($scope.serialTimer) {
      return;
    }
    return $scope.serialTimer = setInterval(function(){
      return $scope.$apply(function(){
        $scope.serial = ($scope.serial + 1) % $scope.data.length;
        return $scope.current = $scope.data[$scope.serial];
      });
    }, 500);
  };
  $scope.data = [];
  $scope.type = [];
  $scope.current = {};
  $scope.aux = {
    pie: d3.layout.pie().sort(null).value(function(it){
      return it.value;
    }),
    arc: d3.svg.arc().outerRadius(radius).innerRadius(0),
    color: d3.scale.category20(),
    bubble: d3.layout.pack().sort(null).size([radius * 2.2, radius * 2.2]).padding(1.5),
    treemap: d3.layout.treemap().sort(null).size([400, 250]).padding(5)
  };
  $scope.viz = {
    pie: [],
    bar: [],
    bubble: [],
    treemap: []
  };
  $scope.$watch('current', function(){
    var k;
    $scope.viz.pie = $scope.aux.pie((function(){
      var i$, ref$, len$, results$ = [];
      for (i$ = 0, len$ = (ref$ = $scope.type).length; i$ < len$; ++i$) {
        k = ref$[i$];
        results$.push({
          name: k,
          value: ~~$scope.current[k]
        });
      }
      return results$;
    }()));
    $scope.viz.bar = (function(){
      var i$, ref$, len$, results$ = [];
      for (i$ = 0, len$ = (ref$ = $scope.type).length; i$ < len$; ++i$) {
        k = ref$[i$];
        results$.push({
          name: k,
          value: ~~$scope.current[k]
        });
      }
      return results$;
    }());
    $scope.viz.bubble = $scope.aux.bubble.nodes({
      children: (function(){
        var i$, ref$, len$, results$ = [];
        for (i$ = 0, len$ = (ref$ = $scope.type).length; i$ < len$; ++i$) {
          k = ref$[i$];
          results$.push({
            name: k,
            value: ~~$scope.current[k]
          });
        }
        return results$;
      }())
    }).filter(function(it){
      return !it.children;
    });
    return $scope.viz.treemap = $scope.aux.treemap.nodes({
      children: (function(){
        var i$, ref$, len$, results$ = [];
        for (i$ = 0, len$ = (ref$ = $scope.type).length; i$ < len$; ++i$) {
          k = ref$[i$];
          results$.push({
            name: k,
            value: ~~$scope.current[k]
          });
        }
        return results$;
      }())
    }).filter(function(it){
      return !it.children;
    });
  }, true);
  return d3.json('data.json', function(data){
    var dataList, i$, ref$, len$, d, obj;
    dataList = [];
    for (i$ = 0, len$ = (ref$ = data[1]).length; i$ < len$; ++i$) {
      d = ref$[i$];
      obj = {};
      data[0].map(fn$);
      dataList.push(obj);
    }
    return $scope.$apply(function(){
      return $scope.data = dataList, $scope.type = data[0].filter(function(it){
        return it !== '時間';
      }), $scope.current = dataList[dataList.length - 1], $scope;
    });
    function fn$(it, i){
      return obj[it] = d[i];
    }
  });
};