// Generated by LiveScript 1.2.0
var join$ = [].join;
$(document).ready(function(){
  var svg, poi, x$, y, x, poiClass, y$, z$;
  svg = d3.select('#svg');
  poi = [[1, "7-11", 3, 1], [2, "全聯", 1, 1], [2, "全家", 3, 1], [2, "基地台", 1, -1], [4, "捷運東門站", 3, 1], [0, "5分", 10, 0], [6, "梅究醫院", 3, -1], [7, "光光書局", 1, 1], [10, "太平洋百貨", 1, 1], [0, "10分", 10, 0], [12, "檜豹瓦斯行", 3, -1], [14, "梅仁藥局", 1, 1], [0, "15分", 10, 0], [17, "科學教育館", 1, 1], [17, "兒童樂園", 1, 1]];
  x$ = svg;
  x$.append('path').attr('class', 'road').attr('d', "M150 50L150 570");
  x$.append('image').attr('xlink:href', "bad.png").attr('x', 75).attr('y', 25).attr('width', 32).attr('height', 32).attr('transform', "translate(-16 -16)");
  x$.append('image').attr('xlink:href', "good.png").attr('x', 225).attr('y', 25).attr('width', 32).attr('height', 32).attr('transform', "translate(-16 -16)");
  y = d3.scale.ordinal().domain((function(){
    var i$, ref$, len$, results$ = [];
    for (i$ = 0, len$ = (ref$ = poi).length; i$ < len$; ++i$) {
      x = ref$[i$];
      results$.push(x[1]);
    }
    return results$;
  }())).rangePoints([55, 570]);
  poiClass = function(it){
    return join$.call(["poi", it[2] > 2 ? "vip" : void 8, it[3] > 0 ? "pos" : void 8, it[3] < 0 ? "neg" : void 8, it[3] === 0 ? "neu" : void 8].filter(function(it){
      return it;
    }), " ");
  };
  y$ = svg.selectAll('circle.poi').data(poi);
  z$ = y$.enter().append('g');
  z$.append('circle').attr('class', poiClass).attr('cx', 150).attr('cy', function(it){
    var v;
    return v = y(it[1]);
  }).attr('r', function(it){
    return 2 + it[2];
  });
  z$.append('text').attr('class', poiClass).attr('x', function(it){
    if (it[3] === 0) {
      return 150;
    } else if (it[3] > 0) {
      return 225;
    } else {
      return 75;
    }
  }).attr('y', function(it){
    return y(it[1]);
  }).attr('text-anchor', 'middle').attr('dominant-baseline', 'central').text(function(it){
    return it[1];
  });
  return y$;
});