// Generated by LiveScript 1.2.0
var coord;
coord = {
  a: 6378137.0,
  b: 6356752.3142451,
  k0: 0.9999,
  dx: 250000,
  dy: 0,
  lng0: 121 * Math.PI / 180,
  init: function(){
    var a, b;
    a = this.a, b = this.b;
    this.e = 1 - Math.pow(b, 2) / Math.pow(a, 2);
    this.e2 = (1 - Math.pow(b, 2) / Math.pow(a, 2)) / (Math.pow(b, 2) / Math.pow(a, 2));
    return this.init = null;
  },
  rad: function(it){
    return it * Math.PI / 180;
  },
  toGws84: function(x, y){
    var a, b, k0, dx, dy, lng0, e, e2, sin, cos, tan, M, mu, e1, J1, J2, J3, J4, fp, C1, T1, R1, N1, D, Q1, Q2, Q3, Q4, lat, Q5, Q6, Q7, lng;
    if (this.init) {
      this.init();
    }
    a = this.a, b = this.b, k0 = this.k0, dx = this.dx, dy = this.dy, lng0 = this.lng0, e = this.e, e2 = this.e2;
    sin = Math.sin, cos = Math.cos, tan = Math.tan;
    x -= dx;
    y -= dy;
    M = y / k0;
    mu = M / (a * (1.0 - e / 4.0 - 3 * Math.pow(e, 2) / 64.0 - 5 * Math.pow(e, 3) / 256.0));
    e1 = (1.0 - Math.sqrt(1.0 - e)) / (1.0 + Math.sqrt(1.0 - e));
    J1 = 3 * e1 / 2 - 27 * Math.pow(e1, 3) / 32.0;
    J2 = 21 * Math.pow(e1, 2) / 16 - 55 * Math.pow(e1, 4) / 32.0;
    J3 = 151 * Math.pow(e1, 3) / 96.0;
    J4 = 1097 * Math.pow(e1, 4) / 512.0;
    fp = mu + J1 * Math.sin(2 * mu) + J2 * Math.sin(4 * mu) + J3 * Math.sin(6 * mu) + J4 * Math.sin(8 * mu);
    C1 = e2 * Math.pow(Math.cos(fp), 2);
    T1 = Math.pow(Math.tan(fp), 2);
    R1 = a * (1 - e) / Math.pow(1 - e * Math.pow(Math.sin(fp), 2), 3.0 / 2.0);
    N1 = a / Math.pow(1 - e * Math.pow(Math.sin(fp), 2), 0.5);
    D = x / (N1 * k0);
    Q1 = N1 * Math.tan(fp) / R1;
    Q2 = Math.pow(D, 2) / 2.0;
    Q3 = (5 + 3 * T1 + 10 * C1 - 4 * Math.pow(C1, 2) - 9 * e2) * Math.pow(D, 4) / 24.0;
    Q4 = (61 + 90 * T1 + 298 * C1 + 45 * Math.pow(T1, 2) - 3 * Math.pow(C1, 2) - 252 * e2) * Math.pow(D, 6) / 720.0;
    lat = fp - Q1 * (Q2 - Q3 + Q4);
    Q5 = D;
    Q6 = (1 + 2 * T1 + C1) * Math.pow(D, 3) / 6;
    Q7 = (5 - 2 * C1 + 28 * T1 - 3 * Math.pow(C1, 2) + 8 * e2 + 24 * Math.pow(T1, 2)) * Math.pow(D, 5) / 120.0;
    lng = lng0 + (Q5 - Q6 + Q7) / Math.cos(fp);
    lat = (lat * 180) / Math.PI;
    lng = (lng * 180) / Math.PI;
    return {
      lat: lat,
      lng: lng
    };
  },
  toTwd97: function(arg$){
    var lat, lng, a, b, k0, dx, dy, lng0, e, e2, sin, cos, tan, ref$, n, nu, p, A, B, C, D, E, S, K1, K2, K3, y, K4, K5, x;
    lat = arg$.lat, lng = arg$.lng;
    if (this.init) {
      this.init();
    }
    a = this.a, b = this.b, k0 = this.k0, dx = this.dx, dy = this.dy, lng0 = this.lng0, e = this.e, e2 = this.e2;
    sin = Math.sin, cos = Math.cos, tan = Math.tan;
    ref$ = [this.rad(lat), this.rad(lng)], lat = ref$[0], lng = ref$[1];
    e = Math.pow(1 - Math.pow(b, 2) / Math.pow(a, 2), 0.5);
    e2 = Math.pow(e, 2) / (1 - Math.pow(e, 2));
    n = (a - b) / (a + b);
    nu = a / Math.pow(1 - Math.pow(e, 2) * Math.pow(sin(lat), 2), 0.5);
    p = lng - lng0;
    A = a * (1 - n + (5 / 4.0) * (Math.pow(n, 2) - Math.pow(n, 3)) + (81 / 64.0) * (Math.pow(n, 4) - Math.pow(n, 5)));
    B = (3 * a * n / 2.0) * (1 - n + (7 / 8.0) * (Math.pow(n, 2) - Math.pow(n, 3)) + (55 / 64.0) * (Math.pow(n, 4) - Math.pow(n, 5)));
    C = (15 * a * Math.pow(n, 2) / 16.0) * (1 - n + (3 / 4.0) * (Math.pow(n, 2) - Math.pow(n, 3)));
    D = (35 * a * Math.pow(n, 3) / 48.0) * (1 - n + (11 / 16.0) * (Math.pow(n, 2) - Math.pow(n, 3)));
    E = (315 * a * Math.pow(n, 4) / 51.0) * (1 - n);
    S = A * lat - B * sin(2 * lat) + C * sin(4 * lat) - D * sin(6 * lat) + E * sin(8 * lat);
    K1 = S * k0;
    K2 = k0 * nu * sin(2 * lat) / 4.0;
    K3 = (k0 * nu * sin(lat) * Math.pow(cos(lat), 3) / 24.0) * (5 - Math.pow(tan(lat), 2) + 9 * e2 * Math.pow(cos(lat), 2) + 4 * Math.pow(e2, 2) * Math.pow(cos(lat), 4));
    y = K1 + K2 * Math.pow(p, 2) + K3 * Math.pow(p, 4);
    K4 = k0 * nu * cos(lat);
    K5 = (k0 * nu * Math.pow(cos(lat), 3) / 6.0) * (1 - Math.pow(tan(lat), 2) + e2 * Math.pow(cos(lat), 2));
    x = K4 * p + K5 * Math.pow(p, 3) + dx;
    return [x, y];
  }
};