// Generated by LiveScript 1.2.0
var mainCtrl;
mainCtrl = function($scope){
  var mapOption, clusterOption, countCamera, map, x$, mc;
  mapOption = {
    center: new google.maps.LatLng(25.048281, 121.5371),
    zoom: 16,
    minZoom: 8,
    maxZoom: 18,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  clusterOption = {
    gridSize: 75,
    maxZoom: 15,
    minimumClusterSize: 1,
    zoomOnClick: true
  };
  countCamera = function(m, numStyles){
    var v;
    v = m.reduce(function(a, b){
      return b.data.count + a;
    }, 0);
    return {
      text: v + "",
      index: parseInt(v / 100)
    };
  };
  map = new google.maps.Map(document.getElementById('map-node'), mapOption);
  google.maps.event.addListenerOnce(map, 'idle', function(){
    return google.maps.event.trigger(map, 'resize');
  });
  setTimeout(function(){
    return $('#map-node').css('width', '100%');
  }, 1000);
  x$ = mc = new MarkerClusterer(map, [], clusterOption);
  x$.setCalculator(countCamera);
  $scope.poi = [];
  $scope.poiIcon = {
    url: 'poi.png',
    size: new google.maps.Size(13, 16),
    origin: new google.maps.Point(0, 0)
  };
  $scope.poiMoreIcon = {
    url: 'poi-more.png',
    size: new google.maps.Size(13, 16),
    origin: new google.maps.Point(0, 0)
  };
  return d3.csv('monitor.csv', function(data){
    var count, hash, i$, len$, item, key, k, m;
    count = 0;
    hash = {};
    for (i$ = 0, len$ = data.length; i$ < len$; ++i$) {
      item = data[i$];
      key = item.lat + "" + item.lng;
      if (!(key in hash)) {
        hash[key] = import$({
          count: 0
        }, item);
      }
      hash[key].count += 1;
    }
    for (k in hash) {
      item = hash[k];
      m = new google.maps.Marker({
        zIndex: 9900000,
        position: new google.maps.LatLng(item.lat, item.lng),
        map: null,
        icon: item.count > 1
          ? $scope.poiMoreIcon
          : $scope.poiIcon
      });
      m.data = item;
      $scope.poi.push(m);
    }
    mc.addMarkers($scope.poi);
    $scope.clusterIsOn = true;
    return $scope.$watch('clusterIsOn', function(v){
      if (v) {
        return mc.addMarkers($scope.poi);
      } else {
        mc.clearMarkers();
        return $scope.poi.map(function(it){
          return it.setMap(map);
        });
      }
    });
  });
};
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}