// Generated by LiveScript 1.2.0
var x$;
x$ = angular.module('main', ['ui.choices']);
x$.controller('main', function($scope){
  $scope.nodes = [];
  import$($scope, {
    randomWidth: false,
    randomHeight: false
  });
  $scope.init = function(){
    var i;
    return $scope.nodes = (function(){
      var i$, to$, results$ = [];
      for (i$ = 0, to$ = 5 + parseInt(Math.random() * 5); i$ <= to$; ++i$) {
        i = i$;
        results$.push({
          w: $scope.randomWidth ? Math.random() * 230 + 30 : 100,
          h: $scope.randomHeight ? Math.random() * 230 + 30 : 100
        });
      }
      return results$;
    }());
  };
  $scope.$watch('randomHeight', $scope.init);
  $scope.$watch('randomWidth', $scope.init);
  return $scope.init();
});
function import$(obj, src){
  var own = {}.hasOwnProperty;
  for (var key in src) if (own.call(src, key)) obj[key] = src[key];
  return obj;
}