// Generated by LiveScript 1.2.0
var epaCtrl;
epaCtrl = function($scope){
  var mapOption, map;
  $scope.name = "近期附近無公害申訴";
  $scope.epas = [];
  mapOption = {
    center: new google.maps.LatLng(25.048281, 121.5371),
    scrollwheel: false,
    zoom: 16,
    minZoom: 8,
    maxZoom: 18,
    mapTypeId: google.maps.MapTypeId.ROADMAP
  };
  map = new google.maps.Map(document.getElementById('map-node'), mapOption);
  google.maps.event.addListenerOnce(map, 'idle', function(){
    return google.maps.event.trigger(map, 'resize');
  });
  setTimeout(function(){
    return $('#map-node').css('width', '100%');
  }, 1000);
  google.maps.event.addListener(map, 'dragend', function(){
    var ll;
    ll = map.getCenter();
    return $.ajax('/epa', {
      method: 'POST',
      data: JSON.stringify({
        lat: ll.lat(),
        lng: ll.lng()
      })
    }).success(function(data){
      var count, i$, len$, item, cat, ret, k;
      count = {};
      for (i$ = 0, len$ = data.length; i$ < len$; ++i$) {
        item = data[i$];
        cat = item.Pollution_Parent;
        count[cat] = (count[cat] || 0) + 1;
      }
      ret = (function(){
        var results$ = [];
        for (k in count) {
          results$.push(k);
        }
        return results$;
      }()).sort(function(a, b){
        return count[b] - count[a];
      });
      return $scope.$apply(function(){
        $scope.epas = ret.map(function(it){
          return [it, count[it]];
        });
        return $scope.name = ret.length ? "附近主要公害類型為" + ret[0] : "近期附近無公害申訴";
      });
    });
  });
  return setTimeout(function(){
    return $('#map-node').width('100%');
  }, 1000);
};