// Generated by LiveScript 1.2.0
var main;
main = function($scope){
  var svgns, svg, c, ani;
  $scope.x = 20;
  $scope.px = 0;
  $scope.blah = [];
  svgns = "http://www.w3.org/2000/svg";
  svg = document.getElementById("svg");
  c = document.createElementNS(svgns, "circle");
  c.setAttribute("cx", "100");
  c.setAttribute("cy", "100");
  c.setAttribute("r", "20");
  c.setAttribute("fill", "red");
  svg.appendChild(c);
  ani = document.createElementNS(svgns, "animate");
  ani.setAttribute("attributeName", "r");
  ani.setAttribute("dur", "1s");
  ani.setAttribute("begin", "indefinite");
  ani.setAttribute("end", "indefinite");
  ani.setAttribute("fill", "remove");
  c.appendChild(ani);
  return setInterval(function(){
    return $scope.$apply(function(){
      var cc;
      $scope.px = $scope.x;
      $scope.x = Math.random() * 100;
      c.setAttribute("r", 999);
      $scope.blah.push([$scope.px, $scope.x]);
      c.removeChild(ani);
      ani.setAttribute("from", $scope.px);
      ani.setAttribute("to", $scope.x);
      cc = svg.getCurrentTime();
      ani.beginElementAt(cc);
      console.log(ani.getStartTime(), svg.getCurrentTime());
      c.appendChild(ani);
      return c.setAttribute("r", $scope.x);
    });
  }, 2000);
};