// Generated by LiveScript 1.2.0
var ref$, w, h, m, circles, bp, ep, pp, score, setup, enemy, bullet, player, mouseMoved, mousePressed, scoring, draw;
ref$ = [800, 600, 10], w = ref$[0], h = ref$[1], m = ref$[2];
circles = [];
bp = [];
ep = [];
pp = {
  x: 0,
  y: h - m - 10
};
score = 0;
setup = function(){
  createCanvas(w, h);
  return fullscreen();
};
enemy = function(v){
  stroke(255, 0, 0);
  beginShape();
  vertex(v.x - v.r, v.y - v.r);
  vertex(v.x, v.y + v.r);
  vertex(v.x + v.r, v.y - v.r);
  vertex(v.x - v.r, v.y - v.r);
  return endShape('Close');
};
bullet = function(v){
  fill(0);
  stroke(0);
  return ellipse(v.x, v.y, v.r, v.r);
};
player = function(){
  stroke(0, 128, 0);
  beginShape();
  vertex(pp.x - 10, pp.y + 10);
  vertex(pp.x, pp.y - 10);
  vertex(pp.x + 10, pp.y + 10);
  vertex(pp.x - 10, pp.y + 10);
  return endShape('Close');
};
mouseMoved = function(){
  return pp.x = mouseX;
};
mousePressed = function(){
  return bp = bp.concat([{
    x: pp.x,
    y: pp.y - 10,
    r: 5
  }]);
};
scoring = function(){
  textSize(32);
  return text("score: " + score, 10, 40);
};
draw = function(){
  var i$, ref$, len$, b, e, r, x, y, j$, ref1$, len1$;
  rect(0, 0, w, h);
  scoring();
  player();
  for (i$ = 0, len$ = (ref$ = bp).length; i$ < len$; ++i$) {
    b = ref$[i$];
    bullet(b);
    b.y -= 5;
  }
  for (i$ = 0, len$ = (ref$ = ep).length; i$ < len$; ++i$) {
    e = ref$[i$];
    enemy(e);
    e.y += 5;
  }
  if (ep.length < 15 && Math.random() > 0.9) {
    r = Math.random() * 10 + 10;
    x = parseInt(Math.random() * (w - 2 * m - 2 * r) + m + r);
    y = m + 10;
    ep.push({
      x: x,
      y: y,
      r: r
    });
  }
  for (i$ = 0, len$ = (ref$ = bp).length; i$ < len$; ++i$) {
    b = ref$[i$];
    for (j$ = 0, len1$ = (ref1$ = ep).length; j$ < len1$; ++j$) {
      e = ref1$[j$];
      if (Math.sqrt(Math.pow(b.x - e.x, 2) + Math.pow(b.y - e.y, 2)) < e.r) {
        e.die = 1;
        b.die = 1;
        score = score + 10;
      }
    }
  }
  for (i$ = 0, len$ = (ref$ = ep).length; i$ < len$; ++i$) {
    e = ref$[i$];
    if (Math.sqrt(Math.pow(pp.x - e.x, 2) + Math.pow(pp.y - e.y, 2)) < e.r) {
      noLoop();
      text("Game Over", w / 2 - 50, h / 2);
    }
  }
  ep = ep.filter(function(it){
    return it.y <= h - m && !it.die;
  });
  return bp = bp.filter(function(it){
    return it.y <= h - m && !it.die;
  });
};