// Generated by LiveScript 1.2.0
var ref$, w, h, m, circles, setup, draw;
ref$ = [640, 480, 10], w = ref$[0], h = ref$[1], m = ref$[2];
circles = [];
setup = function(){
  createCanvas(640, 480);
  return fullscreen();
};
draw = function(){
  var r, x, y, i$, ref$, len$, c;
  rect(0, 0, 640, 480);
  if (mouseIsPressed) {
    fill(0);
  } else {
    fill(255);
  }
  ellipse(mouseX, mouseY, 80, 80);
  if (circles.length < 15 && Math.random() > 0.8) {
    r = Math.random() * 40 + 40;
    x = parseInt(Math.random() * (w - 2 * m - 2 * r) + m + r);
    y = parseInt(Math.random() * (h - 2 * m - 2 * r) + m + r);
    circles.push([x, y, r, 0]);
  }
  for (i$ = 0, len$ = (ref$ = circles).length; i$ < len$; ++i$) {
    c = ref$[i$];
    ellipse(c[0], c[1], c[3], c[3]);
    c[3] = (c[3] * 2 + c[2] * 1) / 3;
  }
  return circles = circles.filter(function(it){
    return it[3] <= it[2] * 0.9999;
  });
};